seed: 1234
gate_set: "16"
steps: 2000
anneal:
  T0: 0.60
  Tmin: 0.06
  direction: "top_down"
  schedule: "cosine"
  phase_scale: 0.5
sigma16:
  s_start: 0.25
  s_end: 0.10
pair:
  route: mi_soft           # << use MI priors (soft)
  repel: true
  mode: "log"              # your current choice; can also try "hard-log"
  eta: 2.0
  prior_strength: 2.0      # how strongly MI prior biases PL/PR (try 1.0–3.0)
  mi_disjoint: true        # prefer disjoint pairs when picking MI pairs
